name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        run: |
          wget https://github.com/TinyTapeout/iverilog/releases/download/v13.0/iverilog_13.0-1_amd64.deb
          sudo apt-get update
          sudo dpkg -i iverilog_13.0-1_amd64.deb

      - name: Run RTL tests
        run: |
          cd test
          make -B

      - name: Upload waveform
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test/tb.fst